my_string = input('Задайте интересующий вас вопрос! ')
print('Кол-во символов введенного текста', len(my_string))
print('Строка в верхнем регистре', my_string.upper())
print('Строка в нижнем регистре', my_string.lower())
print('Строка с удалением пробелов', my_string.replace(' ', ''))
print('Последний символ вводимого текста', my_string[-1])